name: "Reporte de bug"
description: "Reporta un problema reproducible"
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Resumen
      description: Explica brevemente el problema.
      placeholder: "Agrupación incorrecta en fracción decimal al convertir binario → decimal"
    validations: { required: true }

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Detalla los pasos mínimos para provocar el bug.
      placeholder: |
        1) Ir a /conversiones
        2) Ingresar: 1010001011001.00010010 (binario) → decimal
        3) Observar que la fracción se formatea de forma incorrecta
    validations: { required: true }

  - type: textarea
    id: expected_actual
    attributes:
      label: Comportamiento esperado vs. actual
      placeholder: |
        Esperado: ...
        Actual: ...
    validations: { required: true }

  - type: textarea
    id: context
    attributes:
      label: Contexto adicional / logs / capturas
      placeholder: "Capturas de pantalla, registros, enlaces relevantes…"

  - type: input
    id: env
    attributes:
      label: Entorno
      placeholder: "SO/Navegador, versiones (p. ej. macOS 14.5 / Firefox 142)"
