blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/ApocalixDeLuque/binaryx/security/advisories
    about: Please report security vulnerabilities privately via GitHub Security Advisories or email in SECURITY.md.
