blank_issues_enabled: false
contact_links:
  - name: Reportes de seguridad
    url: https://github.com/ApocalixDeLuque/binaryx/security/advisories
    about: Reporta vulnerabilidades de forma privada mediante GitHub Security Advisories o el correo indicado en SECURITY.md.
