name: "Solicitud de mejora"
description: "Propone una funcionalidad o mejora"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / caso de uso
      placeholder: "Necesitamos conversión Decimal ↔ Gray con visualización paso a paso…"
    validations: { required: true }

  - type: textarea
    id: proposal
    attributes:
      label: Propuesta de solución
      placeholder: "Crear componentes en src/components/results/gray-<->binary, añadir pasos y resultado final, integrar en el panel…"
    validations: { required: true }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      placeholder: "Herramienta externa X, pasos manuales, etc."

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options: ["sería genial", "importante", "crítico"]
      default: 0
