name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Typecheck (web)
        working-directory: apps/web
        run: bunx tsc -p tsconfig.json --noEmit

      - name: Test (web)
        working-directory: apps/web
        run: bunx vitest --run

      - name: Build (web)
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
        working-directory: apps/web
        run: bun run build
